permalink: /blog/:year/:month/:day/:title
description: ""
title: "HSBNE"
title_long: "Hackerspace Brisbane"
title_legal: "HSBNE Inc"
hostname: "hsbne.org"
exclude: ['bin']
markdown: kramdown
gems:
  - jekyll-sitemap
